Dream_Housing/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dream_Housing.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

	}
}

Dream_Housing/Controllers/LandingPageController.cs
using Dream_Housing.Utilities;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Dream_Housing.Controllers
{
    public class LandingPageController : Controller
    {
		// GET: LandingPage
		//[Authorize]
		public ActionResult Index()
        {

			// Password Hashing Test
			//string password = "sudipta";
			//Debug.WriteLine("Password: " + password);
			//string hashedPassword = Password.Hash(password);
			//Debug.WriteLine("Hashed Password: " + hashedPassword);
			//Debug.WriteLine("Verify Password: " + Password.Verify(password, hashedPassword));

			return View();
        }
		[Authorize]
		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

		public ActionResult Services()
		{
			ViewBag.Message = "Your services page.";

			return View();
		}

		public ActionResult Project()
		{
			ViewBag.Message = "Your project page.";

			return View();
		}

		public ActionResult Testimonial()
		{
			ViewBag.Message = "Your testimonial page.";

			return View();
		}

		[HttpGet]
		public ActionResult Login()
		{
			//ViewBag.Message = "Your Login page.";
			//ViewBag.AlertType = "alert-danger";
			//ViewBag.AlertTitle = "Error!";
			//ViewBag.AlertMessage = "Invalid username or password.";

			return View();
		}

		[HttpPost]
		public ActionResult Login(string Email, string Password)
		{
			// Check if the email and password match the patterns
			if (!IsValidEmail(Email))
			{
				ViewBag.AlertType = "alert-danger";
				ViewBag.AlertTitle = "Error!";
				ViewBag.AlertMessage = "Invalid Email.";
				return View();
			}

			if (!IsValidPassword(Password))
			{
				ViewBag.AlertType = "alert-danger";
				ViewBag.AlertTitle = "Error!";
				ViewBag.AlertMessage = "Invalid Password.";
				return View();
			}

			// Check if the email and password are correct
			bool emailCorrect = (Email == "test1@gmail.com");
			bool passwordCorrect = (Password == "0testPass@");

			if (!emailCorrect && !passwordCorrect)
			{
				ViewBag.AlertType = "alert-danger";
				ViewBag.AlertTitle = "Error!";
				ViewBag.AlertMessage = "Invalid Email and Password.";
				Console.WriteLine("Both Email And Password are wrong");
			}
			else if (!emailCorrect)
			{
				ViewBag.AlertType = "alert-danger";
				ViewBag.AlertTitle = "Error!";
				ViewBag.AlertMessage = "Wrong Email.";
			}
			else if (!passwordCorrect)
			{
				ViewBag.AlertType = "alert-danger";
				ViewBag.AlertTitle = "Error!";
				ViewBag.AlertMessage = "Wrong Password.";
			}
			else
			{
				// Perform user existence check in the database
				dynamic userExists = null;

				if (userExists != null)
				{
					ViewBag.AlertType = "alert-success";
					ViewBag.AlertTitle = "Success!";
					ViewBag.AlertMessage = "Login Successful.";
				}
				else
				{
					ViewBag.AlertType = "alert-danger";
					ViewBag.AlertTitle = "Error!";
					ViewBag.AlertMessage = "Login Failed.";
					Console.WriteLine("Login Failed because User not found in the 'user' table from the database");
				}
			}

			return View();
		}















		private bool IsValidEmail(string email)
		{
			// Implement your email validation logic here
			// Example: use regular expressions to validate email format

			// Regular expression pattern for validating email addresses
			string emailPattern = @"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$";

			// Use Regex.IsMatch to check if the email matches the pattern
			bool validationResult = Regex.IsMatch(email, emailPattern);

			return validationResult;
		}

		private bool IsValidPassword(string password)
		{
			// Implement your password validation logic here
			// Example: check minimum length, at least one uppercase letter, and at least one digit

			if (string.IsNullOrEmpty(password))
			{
				return false;
			}

			// Check minimum length (e.g., 8 characters)
			if (password.Length < 6 && password.Length > 255)
			{
				return false;
			}

			return true;
		}

	}
}

Dream_Housing/Views/LandingPage/About.cshtml
@{
    ViewBag.Title = "About";
	Layout= "~/Views/Shared/_Layout_Secondary.cshtml";
}


<main>
	<!-- about sectuion start -->
	<div class="about_section layout_padding">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h1 class="about_taital">About Us</h1>
					<p class="about_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All </p>
					<div class="read_bt_1"><a href="#">Read More</a></div>
				</div>
				<div class="col-md-6">
					<div class="about_img">
						<div class="video_bt">
							<div class="play_icon"><img src="~/Content/images/play-icon.png"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- about sectuion end -->
	
</main>

Dream_Housing/Views/LandingPage/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout_Secondary.cshtml";
}
<main>
	<div class="contact_section layout_padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1 class="contact_taital">Contact Us</h1>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="contact_section_2">
				<div class="row">
					<div class="col-md-6">
						<form action="">
							<div class="mail_section_1">
								<input type="text" class="mail_text" placeholder="Name" name="Name">
								<input type="text" class="mail_text" placeholder="Phone Number" name="Phone Number">
								<input type="text" class="mail_text" placeholder="Email" name="Email">
								<textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="Massage"></textarea>
								<div class="send_bt"><a href="#">SEND</a></div>
							</div>
						</form>
					</div>
					<div class="col-md-6 padding_left_15">
						<div class="contact_img"><img src="~/Content/images/contact-img.png"></div>
					</div>
				</div>
			</div>
		</div>
		<div class="map_main">
			<div class="map-responsive">
				<iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&amp;q=Eiffel+Tower+Paris+France" width="600" height="600" frameborder="0" style="border:0; width: 100%;" allowfullscreen=""></iframe>
			</div>
		</div>
	</div>
</main>

Dream_Housing/Views/LandingPage/Login.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="~/Content/login/images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Content/login/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/Content/login/css/main.css">
	<!--===============================================================================================-->
	<style>
		#alertPlaceholder .alert {
			position: fixed;
			top: 20px;
			right: 20px;
			width: 300px; /* Set the width of the alert box */
			z-index: 1050; /* Ensure it appears above other elements */
		}

		#alertPlaceholder .alert .icon {
			display: inline-block;
			margin-right: 10px; /* Space between the icon and the text */
		}
	</style>
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('@Url.Content("~/Content/login/images/bg-01.jpg")');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Account Login
				</span>
				@using (Html.BeginForm("Login", "LandingPage", FormMethod.Post, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
				{
					<div class="wrap-input100 validate-input" data-validate="Enter username">
						@Html.TextBox("Email", null, new { @class = "input100", placeholder = "Email" })
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>
					@Html.ValidationMessage("Email", "", new { @class = "text-danger" })
					@*@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })*@

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						@Html.Password("Password", null, new { @class = "input100", placeholder = "Password" })
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>
					@Html.ValidationMessage("Password", "", new { @class = "text-danger" })

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
				}

				<!-- Alert placeholder -->
				<div id="alertPlaceholder">
					@if (!string.IsNullOrEmpty(ViewBag.AlertMessage))
					{
						<div class="alert @ViewBag.AlertType alert-white rounded">
							<button type="button" data-dismiss="alert" aria-hidden="true" class="close">×</button>
							<div class="icon">
								@if (ViewBag.AlertType == "alert-success")
								{
									<i class="fa fa-check"></i>
								}
								else if (ViewBag.AlertType == "alert-danger")
								{
									<i class="fa fa-times-circle"></i>
								}
								<!-- Add more icons for different alert types as needed -->
							</div>
							<strong>@ViewBag.AlertTitle</strong>
							@ViewBag.AlertMessage
						</div>
					}
				</div>
			</div>
		</div>
	</div>

	<div id="dropDownSelect1"></div>

	<!--===============================================================================================-->
	<script src="~/Content/login/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/Content/login/vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/Content/login/vendor/bootstrap/js/popper.js"></script>
	<script src="~/Content/login/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/Content/login/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="~/Content/login/vendor/daterangepicker/moment.min.js"></script>
	<script src="~/Content/login/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script src="~/Content/login/vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
	<script src="~/Content/login/js/main.js"></script>

	<!-- Script to automatically dismiss alerts after some time -->
	<script>
		$(document).ready(function () {
			window.setTimeout(function () {
				$(".alert").fadeTo(500, 0).slideUp(500, function () {
					$(this).remove();
				});
			}, 4000); // Dismiss alert after 4 seconds
		});
	</script>

</body>
</html>

Dream_Housing/Views/LandingPage/Project.cshtml
@{
    ViewBag.Title = "Project";
    Layout = "~/Views/Shared/_Layout_Secondary.cshtml";
}

<h2>Project</h2>

Dream_Housing/Views/LandingPage/Services.cshtml
@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_Layout_Secondary.cshtml";
}

<h2>Services</h2>

Dream_Housing/Views/LandingPage/Testimonial.cshtml
@{
    ViewBag.Title = "Testimonial";
    Layout = "~/Views/Shared/_Layout_Secondary.cshtml";
}

<h2>Testimonial</h2>

Dream_Housing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- basic -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- mobile metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<!-- site metas -->
	<title>@ViewBag.title</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- bootstrap css -->
	<link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">
	<!-- style css -->
	<link rel="stylesheet" type="text/css" href="~/Content/css/style.css">
	<!-- Responsive-->
	<link rel="stylesheet" href="~/Content/css/responsive.css">
	<!-- fevicon -->
	<link rel="icon" href="~/Content/images/fevicon.png" type="image/gif" />
	<!-- Scrollbar Custom CSS -->
	<link rel="stylesheet" href="~/Content/css/jquery.mCustomScrollbar.min.css">
	<!-- Tweaks for older IEs-->
	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<!-- fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;800&family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
</head>
<body>
	<!-- header top section start -->
	<div class="header_top_section">
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div class="header_top_main">
						<div class="call_text"><a href="#"><i class="fa fa-phone" aria-hidden="true"></i> +01-40-114-6855</a></div>
						<div class="call_text_2"><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i> demo@gmail.com</a></div>
						<div class="call_text_1"><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i> Mordern Tawon Mosco</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- header top section start -->
	<!-- header section start -->
	<div class="header_section">
		<div class="container-fluid">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<div class="logo"><a href="index.html"><img src="~/Content/images/logo.png"></a></div>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							@Html.ActionLink("Home", "Index", "LandingPage", new { area = "" }, new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("Services", "Services", "LandingPage", new { area = "" }, new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("About", "About", "LandingPage", new { area = "" }, new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("Project", "Project", "LandingPage", new { area = "" }, new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("Testimonial", "Testimonial", "LandingPage", new { area = "" }, new { @class = "nav-link" })
						</li>
						<li class="nav-item">
							@Html.ActionLink("Contact Us", "Contact", "LandingPage", new { area = "" }, new { @class = "nav-link" })
						</li>
					</ul>
					<form class="form-inline my-2 my-lg-0">
						<div class="login_text">
							<ul>
								<li>@Html.ActionLink("Login", "Login", "LandingPage", new { area = "" })</li>
								<li><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>
							</ul>
						</div>
						<div class="quote_btn"><a href="#">Get A Quote</a></div>
					</form>
				</div>
			</nav>
		</div>

		@RenderBody()

		<!-- footer section end -->
		<!-- copyright section start -->
		<div class="copyright_section">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<p class="copyright_text">2019 All Rights Reserved. Design by <a href="https://html.design" rel="nofollow">HTML.DESIGN</a> Distribution by <a href="https://themewagon.com">ThemeWagon</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- copyright section end -->
		<!-- Javascript files-->
		<script src="~/Content/js/jquery.min.js"></script>
		<script src="~/Content/js/popper.min.js"></script>
		<script src="~/Content/js/bootstrap.bundle.min.js"></script>
		<script src="~/Content/js/jquery-3.0.0.min.js"></script>
		<script src="~/Content/js/plugin.js"></script>



</body>
</html>

Dream_Housing/Views/Shared/_Layout_Secondary.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- basic -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- mobile metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<!-- site metas -->
	<title>About</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- bootstrap css -->
	<link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">
	<!-- style css -->
	<link rel="stylesheet" type="text/css" href="~/Content/css/style.css">
	<!-- Responsive-->
	<link rel="stylesheet" href="~/Content/css/responsive.css">
	<!-- fevicon -->
	<link rel="icon" href="~/Content/images/fevicon.png" type="image/gif" />
	<!-- Scrollbar Custom CSS -->
	<link rel="stylesheet" href="~/Content/css/jquery.mCustomScrollbar.min.css">
	<!-- Tweaks for older IEs-->
	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<!-- fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;800&family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
</head>
	<body>
		<!-- header top section start -->
		<div class="header_top_section">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="header_top_main">
							<div class="call_text"><a href="#"><i class="fa fa-phone" aria-hidden="true"></i> +01-40-114-6855</a></div>
							<div class="call_text_2"><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i> demo@gmail.com</a></div>
							<div class="call_text_1"><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i> Mordern Tawon Mosco</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- header top section start -->
		<!-- header section start -->
		<div class="header_section header_bg">
			<div class="container-fluid">
				<nav class="navbar navbar-expand-lg navbar-light bg-light">
					<div class="logo"><a href="index.html"><img src="~/Content/images/logo.png"></a></div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item">
								@Html.ActionLink("Home", "Index", "LandingPage", new { area = "" }, new { @class = "nav-link" })
							</li>
							<li class="nav-item">
								@Html.ActionLink("Services", "Services", "LandingPage", new { area = "" }, new { @class = "nav-link" })
							</li>
							<li class="nav-item">
								@Html.ActionLink("About", "About", "LandingPage", new { area = "" }, new { @class = "nav-link" })
							</li>
							<li class="nav-item">
								@Html.ActionLink("Home", "Project", "LandingPage", new { area = "" }, new { @class = "nav-link" })
							</li>
							<li class="nav-item">
								@Html.ActionLink("Testimonial", "Testimonial", "LandingPage", new { area = "" }, new { @class = "nav-link" })
							</li>
							<li class="nav-item">
								@Html.ActionLink("Contact Us", "Contact", "LandingPage", new { area = "" }, new { @class = "nav-link" })
							</li>
						</ul>
						<form class="form-inline my-2 my-lg-0">
							<div class="login_text">
								<ul>
									<li><a href="#">Login</a></li>
									<li><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>
								</ul>
							</div>
							<div class="quote_btn"><a href="#">Get A Quote</a></div>
						</form>
					</div>
				</nav>
			</div>
		</div>
		<!-- header section end -->

		@RenderBody()


		<!-- footer section start -->
		<div class="footer_section layout_padding">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="location_text">
							<ul>
								<li>
									<a href="#"><span class="padding_15"><i class="fa fa-mobile" aria-hidden="true"></i></span> <br>Call +01 1234567890</a>
								</li>
								<li class="active">
									<a href="#"><span class="padding_15"><i class="fa fa-envelope" aria-hidden="true"></i></span> <br>demo@gmail.com</a>
								</li>
								<li>
									<a href="#"><span class="padding_15"><i class="fa fa-map-marker" aria-hidden="true"></i></span> <br>Location</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="footer_section_2">
					<div class="row">
						<div class="col-md-4">
							<h2 class="useful_text">QUICK LINKS</h2>
							<div class="footer_menu">
								<ul>
									<li><a href="index.html">Home</a></li>
									<li><a href="about.html">About</a></li>
									<li><a href="services.html">Services</a></li>
									<li><a href="projects.html">Projects</a></li>
									<li><a href="testimonial.html">Testimonial</a></li>
									<li><a href="blog.html">Blog</a></li>
									<li><a href="contact.html">Contact Us</a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-4">
							<h2 class="useful_text">Work Portfolio</h2>
							<p class="lorem_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem</p>
						</div>
						<div class="col-md-4">
							<h2 class="useful_text">SIGN UP TO OUR NEWSLETTER</h2>
							<div class="form-group">
								<textarea class="update_mail" placeholder="Enter Your Email" rows="5" id="comment" name="Enter Your Email"></textarea>
								<div class="subscribe_bt"><a href="#">Subscribe</a></div>
							</div>
						</div>
					</div>
				</div>
				<div class="social_icon">
					<ul>
						<li>
							<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- footer section end -->
		<!-- copyright section start -->
		<div class="copyright_section">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<p class="copyright_text">2019 All Rights Reserved. Design by <a href="https://html.design" rel="nofollow">HTML.DESIGN</a> Distribution by <a href="https://themewagon.com">ThemeWagon</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- copyright section end -->
		<!-- Javascript files-->
		<script src="~/Content/js/jquery.min.js"></script>
		<script src="~/Content/js/popper.min.js"></script>
		<script src="~/Content/js/bootstrap.bundle.min.js"></script>
		<script src="~/Content/js/jquery-3.0.0.min.js"></script>
		<script src="~/Content/js/plugin.js"></script>
   </body>
</html>